import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  gradient: { flex: 1 },
  flex: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  scroll: {
    flexGrow: 1,
    justifyContent: "center",
    padding: 24,
    paddingVertical: 40,
    maxWidth: 600,
    width: "100%",
    alignSelf: "center",
  },
  crest: {
    width: 96,
    height: 96,
    alignSelf: "center",
    marginBottom: 16,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 28,
    shadowColor: "#8ba4e8",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
  },
  title: {
    fontSize: 24,
    fontFamily: "jakarta-800",
    color: "#1a1f36",
    textAlign: "center",
    marginBottom: 8,
    lineHeight: 32,
  },
  subtitle: {
    fontSize: 14,
    fontFamily: "jakarta-400",
    color: "#6b7a99",
    textAlign: "center",
    marginBottom: 10,
    lineHeight: 20,
  },
  label: {
    fontSize: 14,
    fontFamily: "jakarta-600",
    color: "#6b7a99",
    marginBottom: 6,
    marginTop: 16,
    letterSpacing: 0.3,
  },
  input: {
    backgroundColor: "#f4f6fb",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: "jakarta-400",
    color: "#1a1f36",
    borderWidth: 1,
    borderColor: "#e8ecf4",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  inputDisabled: {
    opacity: 0.5,
  },
  passwordRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  passwordInput: {
    flex: 1,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderRightWidth: 0,
  },
  eyeBtn: {
    backgroundColor: "#f4f6fb",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderColor: "#e8ecf4",
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
    paddingHorizontal: 14,
    justifyContent: "center",
  },
  eyeText: {
    fontSize: 13,
    fontFamily: "jakarta-600",
    color: "#4A6CF7",
    includeFontPadding: false,
  },
  sportRow: { flexDirection: "row", gap: 10, marginTop: 6 },
  sportBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#e8ecf4",
    alignItems: "center",
    backgroundColor: "#f4f6fb",
  },
  sportBtnActive: {
    backgroundColor: "#4A6CF7",
    borderColor: "#4A6CF7",
  },
  sportBtnDisabled: {
    opacity: 0.5,
  },
  sportBtnText: {
    fontSize: 14,
    fontFamily: "jakarta-600",
    color: "#6b7a99",
    includeFontPadding: false,
  },
  sportBtnTextActive: { color: "#fff" },
  bookBtn: {
    marginTop: 28,
    backgroundColor: "#4A6CF7",
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: "#4A6CF7",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  bookBtnDisabled: {
    backgroundColor: "#A0AEC0",
    shadowOpacity: 0,
    elevation: 0,
    opacity: 0.7,
  },
  bookBtnText: {
    color: "#fff",
    fontSize: 17,
    fontFamily: "jakarta-700",
    letterSpacing: 0.3,
    includeFontPadding: false,
  },
  loadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  progressTrack: {
    marginTop: 16,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#e8ecf4",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 3,
    backgroundColor: "#4A6CF7",
  },
  statusBox: {
    marginTop: 20,
    padding: 16,
    borderRadius: 14,
    backgroundColor: "#eef7ee",
  },
  statusText: {
    fontSize: 14,
    fontFamily: "jakarta-400",
    lineHeight: 21,
    color: "#2e7d32",
  },
  dismissBtn: { marginTop: 12, alignSelf: "center" },
  dismissBtnText: { color: "#4A6CF7", fontFamily: "jakarta-600", fontSize: 14 },
  statusBoxError: { backgroundColor: "#fdecea" },
  statusBoxNeutral: { backgroundColor: "#f4f6fb" },
  statusTextError: { color: "#c62828" },
  statusTextNeutral: { color: "#1a1f36" },
  statusBtnRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 16,
  },
  lastBookingBox: {
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginTop: 16,
    alignItems: "center",
    backgroundColor: "#f4f6fb",
  },
  lastBookingRecent: {
    backgroundColor: "#eef7ee",
  },
  lastBookingText: {
    fontSize: 13,
    color: "#6b7a99",
    fontFamily: "jakarta-500",
  },
  lastBookingTextRecent: {
    color: "#2e7d32",
  },
  debugPanel: {
    backgroundColor: "#1a1f36",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  debugHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  debugTitle: {
    color: "#ff6b6b",
    fontFamily: "jakarta-700",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  debugClose: {
    color: "#ff6b6b",
    fontSize: 16,
    fontFamily: "jakarta-700",
    paddingHorizontal: 4,
  },
  debugRow: {
    flexDirection: "row",
    gap: 8,
  },
  debugBtn: {
    flex: 1,
    backgroundColor: "#2d3352",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  debugBtnReset: {
    backgroundColor: "#4a2030",
  },
  debugBtnText: {
    color: "#fff",
    fontSize: 12,
    fontFamily: "jakarta-600",
  },
  disclaimer: {
    marginTop: 24,
    fontSize: 13,
    fontFamily: "jakarta-400",
    color: "#99a4be",
    textAlign: "center",
    lineHeight: 18,
    includeFontPadding: false,
  },
});
