import { StyleSheet } from "react-native";
import { theme } from "../../theme";

const { colors, fontFamily, fontSize, radii, shadows, space } = theme;

export const styles = StyleSheet.create({
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  flex: { flex: 1 },
  scroll: {
    flexGrow: 1,
    justifyContent: "center",
    padding: space[24],
    paddingVertical: space[20],
    maxWidth: 600,
    width: "100%",
    alignSelf: "center",
  },
  crest: {
    width: 96,
    height: 96,
    alignSelf: "center",
    marginBottom: space[16],
  },
  title: {
    fontSize: fontSize["2xl"],
    fontFamily: fontFamily.extrabold,
    color: colors.textPrimary,
    textAlign: "center",
    marginBottom: space[8],
    lineHeight: 32,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: space[8],
    marginBottom: space[8],
  },
  betaBadge: {
    backgroundColor: "#b0c8ee",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    marginTop: -2,
  },
  betaText: {
    color: "#fff",
    fontSize: fontSize.xs,
    fontFamily: fontFamily.bold,
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: fontSize.md,
    fontFamily: fontFamily.regular,
    color: colors.textMuted,
    textAlign: "center",
    marginBottom: space[10],
    lineHeight: 20,
  },
  label: {
    fontSize: fontSize.md,
    fontFamily: fontFamily.semibold,
    color: colors.textMuted,
    marginBottom: space[6],
    marginTop: space[16],
    letterSpacing: 0.3,
  },
  input: {
    backgroundColor: colors.surfaceInput,
    borderRadius: radii.md,
    paddingHorizontal: space[16],
    paddingVertical: space[14],
    fontSize: fontSize.lg,
    fontFamily: fontFamily.regular,
    color: colors.textPrimary,
    borderWidth: 1,
    borderColor: colors.border,
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  inputDisabled: {
    opacity: 0.5,
  },
  passwordRow: {
    position: "relative",
  },
  passwordInput: {
    paddingRight: 72,
  },
  eyeBtn: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    paddingHorizontal: space[14],
    justifyContent: "center",
  },
  eyeText: {
    fontSize: fontSize.sm,
    fontFamily: fontFamily.semibold,
    color: colors.primary,
    includeFontPadding: false,
  },
  sportRow: { flexDirection: "row", gap: space[10], marginTop: space[6] },
  sportBtn: {
    flex: 1,
    paddingVertical: space[14],
    borderRadius: radii.md,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceInput,
  },
  sportBtnActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  sportBtnDisabled: {
    opacity: 0.5,
  },
  sportBtnText: {
    fontSize: fontSize.md,
    fontFamily: fontFamily.semibold,
    color: colors.textMuted,
    includeFontPadding: false,
    textAlign: "center",
  },
  sportBtnTextActive: { color: colors.textOnPrimary },
  bookBtn: {
    marginTop: space[28],
    backgroundColor: colors.primary,
    paddingVertical: space[18],
    borderRadius: radii.lg,
    alignItems: "center",
    ...shadows.button,
  },
  bookBtnDisabled: {
    backgroundColor: colors.surfaceDisabled,
    shadowOpacity: 0,
    elevation: 0,
    opacity: 0.7,
  },
  bookBtnText: {
    color: colors.textOnPrimary,
    fontSize: fontSize.xl,
    fontFamily: fontFamily.bold,
    letterSpacing: 0.3,
    includeFontPadding: false,
  },
  loadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: space[10],
  },
  progressTrack: {
    marginTop: space[16],
    height: 6,
    borderRadius: radii.xs,
    backgroundColor: colors.surfaceInput,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: radii.xs,
    backgroundColor: colors.primary,
  },
  statusBox: {
    marginTop: space[20],
    padding: space[16],
    borderRadius: radii.md,
    backgroundColor: colors.successBackground,
  },
  statusText: {
    fontSize: fontSize.md,
    fontFamily: fontFamily.regular,
    lineHeight: 21,
    color: colors.successText,
  },
  dismissBtn: { marginTop: space[12], alignSelf: "center" },
  dismissBtnText: {
    color: colors.textMuted,
    fontFamily: fontFamily.semibold,
    fontSize: fontSize.md,
  },
  statusBoxError: { backgroundColor: colors.errorBackground },
  statusBoxNeutral: { backgroundColor: colors.surfaceInput },
  statusTextError: { color: colors.errorText },
  statusTextNeutral: { color: colors.textPrimary },
  lastBookingBox: {
    backgroundColor: colors.surface,
    borderRadius: radii.xl,
    paddingVertical: space[12],
    paddingHorizontal: space[18],
    marginTop: space[16],
    marginBottom: space[16],
    alignItems: "center",
    ...shadows.subtle,
  },
  lastBookingText: {
    fontSize: fontSize.md,
    color: colors.textMuted,
    fontFamily: fontFamily.medium,
  },
  lastBookingTick: {
    color: colors.successText,
    fontFamily: fontFamily.bold,
  },
  nudgePill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space[10],
    backgroundColor: colors.warningBackground,
    borderRadius: radii.lg,
    paddingVertical: space[6],
    paddingHorizontal: space[10],
    marginTop: space[8],
  },
  nudgeText: {
    fontSize: fontSize.md,
    fontFamily: fontFamily.regular,
    color: colors.warningText,
    includeFontPadding: false,
  },
  disclaimer: {
    marginTop: space[24],
    fontSize: fontSize.sm,
    fontFamily: fontFamily.regular,
    color: colors.textMuted,
    textAlign: "center",
    lineHeight: 18,
    includeFontPadding: false,
  },
  saveOnDeviceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: space[10],
    marginTop: space[14],
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: radii.sm,
    borderWidth: 1.5,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surfaceInput,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkboxTick: {
    color: colors.textOnPrimary,
    fontSize: fontSize.xs,
    fontFamily: fontFamily.bold,
    lineHeight: 14,
    includeFontPadding: false,
  },
  saveOnDeviceLabel: {
    flex: 1,
    fontSize: fontSize.sm,
    fontFamily: fontFamily.regular,
    color: colors.textMuted,
  },
  faqTitle: {
    fontSize: fontSize.md,
    fontFamily: fontFamily.semibold,
    color: colors.textMuted,
    letterSpacing: 0.3,
    marginBottom: space[4],
  },
  faqRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: space[14],
  },
  faqQuestion: {
    flex: 1,
    fontSize: fontSize.md,
    fontFamily: fontFamily.semibold,
    color: colors.textPrimary,
    marginRight: space[8],
  },
  faqAnswer: {
    fontSize: fontSize.md,
    fontFamily: fontFamily.regular,
    color: colors.textMuted,
    lineHeight: 22,
    paddingBottom: space[14],
  },
  faqDivider: {
    height: 1,
    backgroundColor: colors.border,
  },
  faqMeasureHelper: {
    position: "absolute",
    opacity: 0,
    left: 0,
    right: 0,
  },
});
